// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQDwli8TZhYg1yV0BAxfaPoA9sxkAtDQw',
    appId: '1:129116938699:web:PLACEHOLDER',
    messagingSenderId: '129116938699',
    projectId: 'i-spoon-auth',
    authDomain: 'i-spoon-auth.firebaseapp.com',
    storageBucket: 'i-spoon-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIWOCzZd82_Mf0zWGVpjN8CzGc5FYFMmY',
    appId: '1:129116938699:android:efe45e648dda46c74e564e',
    messagingSenderId: '129116938699',
    projectId: 'i-spoon-auth',
    storageBucket: 'i-spoon-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDwli8TZhYg1yV0BAxfaPoA9sxkAtDQw',
    appId: '1:129116938699:ios:PLACEHOLDER',
    messagingSenderId: '129116938699',
    projectId: 'i-spoon-auth',
    storageBucket: 'i-spoon-auth.appspot.com',
    iosBundleId: 'com.example.smartspoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQDwli8TZhYg1yV0BAxfaPoA9sxkAtDQw',
    appId: '1:129116938699:macos:PLACEHOLDER',
    messagingSenderId: '129116938699',
    projectId: 'i-spoon-auth',
    storageBucket: 'i-spoon-auth.appspot.com',
    iosBundleId: 'com.example.smartspoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQDwli8TZhYg1yV0BAxfaPoA9sxkAtDQw',
    appId: '1:129116938699:windows:PLACEHOLDER',
    messagingSenderId: '129116938699',
    projectId: 'i-spoon-auth',
    storageBucket: 'i-spoon-auth.appspot.com',
  );
}
